version: "3"
services:
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Los Angeles"
      - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - ../data/tv:/tv
      - ../data/downloads:/downloads
    ports:
      - 9031:8989
    restart: unless-stopped
