services:
  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - /mnt/containers/code-server/config:/config
      - /mnt/containers:/config/workspace/containers
    ports:
      - 8443:8443
    restart: unless-stopped
