bind_host: 0.0.0.0
bind_port: 3000
beta_bind_port: 0
users:
  - name: admin
    password: $2a$10$nrdkHHhePQxll0x7aobz6uA.mWhRtYZlbzI8Kyyq.OM7K00.2p0JG
auth_attempts: 5
block_auth_min: 15
http_proxy: ""
language: ""
debug_pprof: false
web_session_ttl: 720
dns:
  bind_hosts:
    - 0.0.0.0
  port: 53
  statistics_interval: 30
  querylog_enabled: false
  querylog_file_enabled: true
  querylog_interval: 720h
  querylog_size_memory: 1000
  anonymize_client_ip: false
  protection_enabled: true
  blocking_mode: default
  blocking_ipv4: ""
  blocking_ipv6: ""
  blocked_response_ttl: 10
  parental_block_host: family-block.dns.adguard.com
  safebrowsing_block_host: standard-block.dns.adguard.com
  ratelimit: 20
  ratelimit_whitelist: []
  refuse_any: true
  upstream_dns:
    - 192.168.0.1
  upstream_dns_file: ""
  bootstrap_dns:
    - 9.9.9.10
    - 149.112.112.10
    - 2620:fe::10
    - 2620:fe::fe:10
  all_servers: false
  fastest_addr: false
  fastest_timeout: 1s
  allowed_clients: []
  disallowed_clients: []
  blocked_hosts:
    - version.bind
    - id.server
    - hostname.bind
  trusted_proxies:
    - 127.0.0.0/8
    - ::1/128
  cache_size: 4194304
  cache_ttl_min: 0
  cache_ttl_max: 0
  cache_optimistic: false
  bogus_nxdomain: []
  aaaa_disabled: false
  enable_dnssec: false
  edns_client_subnet: false
  max_goroutines: 300
  handle_ddr: true
  ipset: []
  ipset_file: ""
  filtering_enabled: true
  filters_update_interval: 168
  parental_enabled: false
  safesearch_enabled: false
  safebrowsing_enabled: false
  safebrowsing_cache_size: 1048576
  safesearch_cache_size: 1048576
  parental_cache_size: 1048576
  cache_time: 30
  rewrites: []
  blocked_services: []
  upstream_timeout: 10s
  private_networks: []
  use_private_ptr_resolvers: true
  local_ptr_upstreams: []
  serve_http3: false
  use_http3_upstreams: false
tls:
  enabled: false
  server_name: ""
  force_https: false
  port_https: 443
  port_dns_over_tls: 853
  port_dns_over_quic: 784
  port_dnscrypt: 0
  dnscrypt_config_file: ""
  allow_unencrypted_doh: false
  certificate_chain: ""
  private_key: ""
  certificate_path: ""
  private_key_path: ""
  strict_sni_check: false
filters:
  - enabled: true
    url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
    name: AdGuard DNS filter
    id: 1
  - enabled: true
    url: https://adaway.org/hosts.txt
    name: AdAway Default Blocklist
    id: 2
  - enabled: true
    url: http://sbc.io/hosts/hosts
    name: Steven Black
    id: 1631391020
  - enabled: true
    url: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
    name: https://raw.githubusercontent.com/PolishFiltersTeam/KADhosts/master/KADhosts.txt
    id: 1631391021
  - enabled: true
    url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
    name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Spam/hosts
    id: 1631391022
  - enabled: true
    url: https://v.firebog.net/hosts/static/w3kbl.txt
    name: https://v.firebog.net/hosts/static/w3kbl.txt
    id: 1631391023
  - enabled: true
    url: https://v.firebog.net/hosts/Admiral.txt
    name: https://v.firebog.net/hosts/Admiral.txt
    id: 1631391024
  - enabled: true
    url: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
    name: https://raw.githubusercontent.com/anudeepND/blacklist/master/adservers.txt
    id: 1631391025
  - enabled: true
    url: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    name: https://s3.amazonaws.com/lists.disconnect.me/simple_ad.txt
    id: 1631391026
  - enabled: true
    url: https://v.firebog.net/hosts/Easylist.txt
    name: https://v.firebog.net/hosts/Easylist.txt
    id: 1631391027
  - enabled: true
    url: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    name: https://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=0&mimetype=plaintext
    id: 1631391028
  - enabled: true
    url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
    name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/UncheckyAds/hosts
    id: 1631391029
  - enabled: true
    url: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
    name: https://raw.githubusercontent.com/bigdargon/hostsVN/master/hosts
    id: 1631391030
  - enabled: true
    url: https://v.firebog.net/hosts/Easyprivacy.txt
    name: https://v.firebog.net/hosts/Easyprivacy.txt
    id: 1631391031
  - enabled: true
    url: https://v.firebog.net/hosts/Prigent-Ads.txt
    name: https://v.firebog.net/hosts/Prigent-Ads.txt
    id: 1631391032
  - enabled: true
    url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
    name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.2o7Net/hosts
    id: 1631391033
  - enabled: true
    url: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    name: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt
    id: 1631391034
  - enabled: true
    url: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
    name: https://hostfiles.frogeye.fr/firstparty-trackers-hosts.txt
    id: 1631391035
  - enabled: true
    url: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
    name: https://raw.githubusercontent.com/DandelionSprout/adfilt/master/Alternate%20versions%20Anti-Malware%20List/AntiMalwareHosts.txt
    id: 1631391036
  - enabled: true
    url: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
    name: https://osint.digitalside.it/Threat-Intel/lists/latestdomains.txt
    id: 1631391037
  - enabled: true
    url: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
    name: https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
    id: 1631391038
  - enabled: true
    url: https://v.firebog.net/hosts/Prigent-Crypto.txt
    name: https://v.firebog.net/hosts/Prigent-Crypto.txt
    id: 1631391039
  - enabled: true
    url: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
    name: https://bitbucket.org/ethanr/dns-blacklists/raw/8575c9f96e5b4a1308f2f12394abd86d0927a4a0/bad_lists/Mandiant_APT1_Report_Appendix_D.txt
    id: 1631391040
  - enabled: true
    url: https://phishing.army/download/phishing_army_blocklist_extended.txt
    name: https://phishing.army/download/phishing_army_blocklist_extended.txt
    id: 1631391041
  - enabled: true
    url: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
    name: https://gitlab.com/quidsup/notrack-blocklists/raw/master/notrack-malware.txt
    id: 1631391042
  - enabled: true
    url: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
    name: https://raw.githubusercontent.com/Spam404/lists/master/main-blacklist.txt
    id: 1631391043
  - enabled: true
    url: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
    name: https://raw.githubusercontent.com/FadeMind/hosts.extras/master/add.Risk/hosts
    id: 1631391044
  - enabled: true
    url: https://urlhaus.abuse.ch/downloads/hostfile/
    name: https://urlhaus.abuse.ch/downloads/hostfile/
    id: 1631391045
  - enabled: true
    url: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
    name: https://zerodot1.gitlab.io/CoinBlockerLists/hosts_browser
    id: 1631391046
whitelist_filters: []
user_rules:
  - '@@||plausible.io^'
dhcp:
  enabled: false
  interface_name: ""
  local_domain_name: lan
  dhcpv4:
    gateway_ip: ""
    subnet_mask: ""
    range_start: ""
    range_end: ""
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []
  dhcpv6:
    range_start: ""
    lease_duration: 86400
    ra_slaac_only: false
    ra_allow_slaac: false
clients:
  runtime_sources:
    whois: true
    arp: true
    rdns: true
    dhcp: true
    hosts: true
  persistent: []
log_file: ""
log_max_backups: 0
log_max_size: 100
log_max_age: 3
log_compress: false
log_localtime: false
verbose: false
os:
  group: ""
  user: ""
  rlimit_nofile: 0
schema_version: 14
