services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/containers/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
