version: '3.3'
services:
    czkawka:
        container_name: czkawka
        restart: unless-stopped
        ports:
            - '5800:5800'
        volumes:
            - './config:/config:rw'
            - '../photoprism/originals:/storage:rw'
        image: jlesage/czkawka
        environment:
            - PUID=1000
            - PGID=1000
