services:
  czkawka:
    image: jlesage/czkawka
    container_name: czkawka
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - "5800:5800"
    volumes:
      - "/mnt/containers/czkawka/config:/config:rw"
      - "/mnt/containers/photoprism/originals:/storage:rw"
    restart: unless-stopped
