services:
  home-assistant:
    container_name: homeassistant
    restart: unless-stopped
    environment:
      - TZ=America/Vancouver
    volumes:
      - /var/containers/homeassistant/config:/config
    network_mode: host
    image: "ghcr.io/home-assistant/home-assistant:stable"
