---
version: "3"
services:
  watchtower:
    container_name: watchtower
    environment:
      - WATCHTOWER_SCHEDULE=0 0 5 * * 1 # s m h dom mon dow
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    image: containrrr/watchtower
    restart: always
