version: '3.3'
services:
  nginx:
    container_name: nginx 
    ports:
      - '9300:80'
    volumes:
      - './html:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/nginx.conf'
    image: nginx
    restart: unless-stopped
