services:
  nginx:
    image: nginx:1.27.2
    container_name: nginx
    ports:
      - "9300:80"
    volumes:
      - "/mnt/containers/nginx/html:/usr/share/nginx/html"
      - "/mnt/containers/nginx/nginx.conf:/etc/nginx/nginx.conf"
    restart: unless-stopped
