services:
  adguardhome:
    image: adguard/adguardhome # image has no tags
    container_name: adguardhome
    ports:
      - 53:53/tcp # dns
      - 53:53/udp # dns
      - 784:784/udp # dns-over-quic
      - 853:853/tcp # dns-over-tls/quic
      - 3000:3000/tcp # web ui
      - 3001:80/tcp # web ui
      - 3002:443/tcp # web ui
      - 3002:443/udp # web ui
      - 8853:8853/udp # dns-over-quic
    volumes:
      - /mnt/containers/adguardhome/data:/opt/adguardhome/work
      - /mnt/containers/adguardhome/config:/opt/adguardhome/conf
    restart: unless-stopped
