---
version: "3"
services:
  portainer:
    container_name: portainer
    restart: always
    ports:
      - 3000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment:
      - PUID=1000
      - PGID=1000
    image: portainer/portainer-ce
