version: "3"
services:
  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK_SET=022 #optional
    volumes:
      - ./config:/config
      - ../data/music:/music
      - ../data/downloads:/downloads
    ports:
      - 9034:8686
    restart: unless-stopped
