name: Docker CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - run: sudo ss -tulw | grep 53
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            adguardhome/docker-compose.yml
