name: Docker CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      # need checkout before using compose-action
      - uses: actions/checkout@v3
      - run: |
          cd adguardhome
          docker-compose pull
          sudo systemctl disable systemd-resolved.service
          sudo systemctl stop systemd-resolved
          docker-compose up -d
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: |
            bazarr/docker-compose.yml
