name: Docker CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      # custom script for AdGuardHome because we need to disable resolved
      - run: |
          cd adguardhome
          docker-compose pull
          systemctl disable systemd-resolved.service 
          docker-compose up -d
          docker-compose down
          systemctl enable systemd-resolved.service
        if: ${{ env.ACT == false }}
      # test the rest of the containers
      - run: |
          docker-compose -f bazarr/docker-compose.yml up -d
          docker-compose -f code-server/docker-compose.yml up -d
          docker-compose -f czkawka/docker-compose.yml up -d
          docker-compose -f dozzle/docker-compose.yml up -d
          docker-compose -f homeassistant/docker-compose.yml up -d
