services:
  npm:
    container_name: npm
    image: "jc21/nginx-proxy-manager:latest"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    environment:
      # These are the settings to access your db
      DB_MYSQL_HOST: "192.168.0.20"
      DB_MYSQL_PORT: 9230
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      DISABLE_IPV6: "true"
    volumes:
      - /mnt/containers/npm/data:/data
      - /mnt/containers/npm/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm-db

  npm-db:
    container_name: npm-db
    image: "jc21/mariadb-aria:latest"
    restart: always
    ports:
      - "9230:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "npm"
      MYSQL_DATABASE: "npm"
      MYSQL_USER: "npm"
      MYSQL_PASSWORD: "npm"
    volumes:
      - /mnt/containers/npm/db:/var/lib/mysql
