services:
  npm:
    container_name: npm
    image: "jc21/nginx-proxy-manager:2.10.3"
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - /mnt/containers/npm/data:/data
      - /mnt/containers/npm/letsencrypt:/etc/letsencrypt
